set(HEADERS_LIST
    include/Node.hpp
    include/Token.hpp
    include/TokenList.hpp
    include/LexicalAnalyzer.hpp
    include/SyntacticAnalyzer.hpp
    include/VariadicTable.hpp
    include/Utils.hpp
    include/Logger.hpp
    include/symbolTable/Type.hpp
    include/symbolTable/Symbol.hpp
    include/symbolTable/SymbolTable.hpp
    include/symbolTable/ReturnValue.hpp
)

set(SOURCES_LIST
    src/main.cpp
    src/Node.cpp
    src/Token.cpp
    src/TokenList.cpp
    src/LexicalAnalyzer.cpp
    src/SyntacticAnalyzer.cpp
    src/Utils.cpp
    src/Logger.cpp
    src/symbolTable/Type.cpp
    src/symbolTable/Symbol.cpp
    src/symbolTable/SymbolTable.cpp
    src/symbolTable/ReturnValue.cpp
)